In [2]:
import numpy as np
n = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
n[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
n[2:]

array([[7, 8, 9]])